
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "Database",
    module_name = "Database",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
    
    ],
    visibility = ["//visibility:public"]
)


# bazel build //BazelExample/Submodule/Database:Database --apple_platform_type=ios
