load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "App",
    module_name = "App",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [],
    visibility = ["//visibility:public"]
)
